In [181]:
import numpy as np 
import pandas as pd 
import seaborn as sns 
import matplotlib.pyplot as plt

In [182]:
import chardet

with open("movies.dat", "rb") as file:
    raw_data = file.read()

result = chardet.detect(raw_data)

print(result)

{'encoding': 'ISO-8859-1', 'confidence': 0.73, 'language': ''}

In [183]:
df1 = pd.read_csv('movies.dat',sep='::',names=['Movie_id','Title','Generes'],encoding='ISO-8859-1')
df1

C:\Users\hp\AppData\Local\Temp\ipykernel_21476\3351226248.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df1 = pd.read_csv('movies.dat',sep='::',names=['Movie_id','Title','Generes'],encoding='ISO-8859-1')

      Movie_id  ...                       Generes
0            1  ...   Animation|Children's|Comedy
1            2  ...  Adventure|Children's|Fantasy
2            3  ...                Comedy|Romance
3            4  ...                  Comedy|Drama
4            5  ...                        Comedy
...        ...  ...                           ...
3878      3948  ...                        Comedy
3879      3949  ...                         Drama
3880      3950  ...                         Drama
3881      3951  ...                         Drama
3882      3952  ...                Drama|Thriller

[3883 rows x 3 columns]

In [184]:
df1['Generes'] = df1['Generes'].str.split('|').explode("Generes")
df1['Generes']

0        Animation
1       Children's
2           Comedy
3        Adventure
4       Children's
           ...
3878       Mystery
3879      Thriller
3880        Comedy
3881       Romance
3882       Romance
Name: Generes, Length: 3883, dtype: object

In [185]:
df2 = pd.read_csv('ratings.dat',sep='::',names=['User_id','Movie_id','rating','Time_stamp'],encoding='ISO-8859-1')
df2

C:\Users\hp\AppData\Local\Temp\ipykernel_21476\1434888210.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df2 = pd.read_csv('ratings.dat',sep='::',names=['User_id','Movie_id','rating','Time_stamp'],encoding='ISO-8859-1')

         User_id  Movie_id  rating  Time_stamp
0              1      1193       5   978300760
1              1       661       3   978302109
2              1       914       3   978301968
3              1      3408       4   978300275
4              1      2355       5   978824291
...          ...       ...     ...         ...
1000204     6040      1091       1   956716541
1000205     6040      1094       5   956704887
1000206     6040       562       5   956704746
1000207     6040      1096       4   956715648
1000208     6040      1097       4   956715569

[1000209 rows x 4 columns]

In [186]:
df3 = pd.read_csv('users.dat',sep='::',names=['User_id','gender','age','occupation','zip_code'],encoding='ISO-8859-1')
df3

C:\Users\hp\AppData\Local\Temp\ipykernel_21476\1862943530.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df3 = pd.read_csv('users.dat',sep='::',names=['User_id','gender','age','occupation','zip_code'],encoding='ISO-8859-1')

      User_id gender  age  occupation zip_code
0           1      F    1          10    48067
1           2      M   56          16    70072
2           3      M   25          15    55117
3           4      M   45           7    02460
4           5      M   25          20    55455
...       ...    ...  ...         ...      ...
6035     6036      F   25          15    32603
6036     6037      F   45           1    76006
6037     6038      F   56           1    14706
6038     6039      F   45           0    01060
6039     6040      M   25           6    11106

[6040 rows x 5 columns]

__EDA OF Movies dataset__

In [187]:
df1.shape

(3883, 3)

In [188]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3883 entries, 0 to 3882
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Movie_id  3883 non-null   int64
 1   Title     3883 non-null   object
 2   Generes   3883 non-null   object
dtypes: int64(1), object(2)
memory usage: 91.1+ KB

In [189]:
df1.isnull().sum()

Movie_id    0
Title       0
Generes     0
dtype: int64

In [190]:
df1.describe()

          Movie_id
count  3883.000000
mean   1986.049446
std    1146.778349
min       1.000000
25%     982.500000
50%    2010.000000
75%    2980.500000
max    3952.000000

__EDA of rating dataset__

In [191]:
df2.shape

(1000209, 4)

In [192]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000209 entries, 0 to 1000208
Data columns (total 4 columns):
 #   Column      Non-Null Count    Dtype
---  ------      --------------    -----
 0   User_id     1000209 non-null  int64
 1   Movie_id    1000209 non-null  int64
 2   rating      1000209 non-null  int64
 3   Time_stamp  1000209 non-null  int64
dtypes: int64(4)
memory usage: 30.5 MB

In [193]:
df2.isnull().sum()

User_id       0
Movie_id      0
rating        0
Time_stamp    0
dtype: int64

In [194]:
df2.duplicated().sum()

np.int64(0)

In [195]:
df2['rating'].value_counts().sort_index(ascending=False)

rating
5    226310
4    348971
3    261197
2    107557
1     56174
Name: count, dtype: int64

In [196]:
df2['Movie_id'].nunique()

3706

In [197]:
df2['User_id'].nunique()

6040

In [198]:
df2.describe()

            User_id      Movie_id        rating    Time_stamp
count  1.000209e+06  1.000209e+06  1.000209e+06  1.000209e+06
mean   3.024512e+03  1.865540e+03  3.581564e+00  9.722437e+08
std    1.728413e+03  1.096041e+03  1.117102e+00  1.215256e+07
min    1.000000e+00  1.000000e+00  1.000000e+00  9.567039e+08
25%    1.506000e+03  1.030000e+03  3.000000e+00  9.653026e+08
50%    3.070000e+03  1.835000e+03  4.000000e+00  9.730180e+08
75%    4.476000e+03  2.770000e+03  4.000000e+00  9.752209e+08
max    6.040000e+03  3.952000e+03  5.000000e+00  1.046455e+09

__EDA of Users dataset__

In [199]:
df3.shape

(6040, 5)

In [200]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6040 entries, 0 to 6039
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   User_id     6040 non-null   int64
 1   gender      6040 non-null   object
 2   age         6040 non-null   int64
 3   occupation  6040 non-null   int64
 4   zip_code    6040 non-null   object
dtypes: int64(3), object(2)
memory usage: 236.1+ KB

In [201]:
df3.isnull().sum()

User_id       0
gender        0
age           0
occupation    0
zip_code      0
dtype: int64

In [202]:
df3.describe()

           User_id          age   occupation
count  6040.000000  6040.000000  6040.000000
mean   3020.500000    30.639238     8.146854
std    1743.742145    12.895962     6.329511
min       1.000000     1.000000     0.000000
25%    1510.750000    25.000000     3.000000
50%    3020.500000    25.000000     7.000000
75%    4530.250000    35.000000    14.000000
max    6040.000000    56.000000    20.000000

In [203]:
df3['zip_code'] = df3['zip_code'].str.split('-').str[0].astype(int)
df3['zip_code']

0       48067
1       70072
2       55117
3        2460
4       55455
        ...
6035    32603
6036    76006
6037    14706
6038     1060
6039    11106
Name: zip_code, Length: 6040, dtype: int64

__Merge Movies data with rating data and users data__

In [204]:
n_df = df2.merge(df1, on='Movie_id',how='left')
df = n_df.merge(df3, on='User_id',how='left')
df

         User_id  Movie_id  rating  ...  age occupation zip_code
0              1      1193       5  ...    1         10    48067
1              1       661       3  ...    1         10    48067
2              1       914       3  ...    1         10    48067
3              1      3408       4  ...    1         10    48067
4              1      2355       5  ...    1         10    48067
...          ...       ...     ...  ...  ...        ...      ...
1000204     6040      1091       1  ...   25          6    11106
1000205     6040      1094       5  ...   25          6    11106
1000206     6040       562       5  ...   25          6    11106
1000207     6040      1096       4  ...   25          6    11106
1000208     6040      1097       4  ...   25          6    11106

[1000209 rows x 10 columns]

In [205]:
df.shape

(1000209, 10)

In [206]:
df.sample(5)

        User_id  Movie_id  rating  Time_stamp  ... gender age occupation  zip_code
706094     4229      2028       3   965312138  ...      M  35         17     94010
943132     5687       173       2   958602958  ...      F   1          0     55403
200284     1230      1690       3   974842057  ...      M  25         11     95125
709432     4254      1663       5   965306775  ...      M  25         17     38654
845709     5083      2571       4   962418953  ...      M  25          4     16803

[5 rows x 10 columns]

In [207]:
user_movie_matrix = df.pivot_table(
    index = 'User_id',
    columns='Movie_id',
    values='rating'
)

In [208]:
user_movie_matrix.shape

(6040, 3706)

In [209]:
user_movie_matrix.head()

Movie_id  1     2     3     4     5     ...  3948  3949  3950  3951  3952
User_id                                 ...
1          5.0   NaN   NaN   NaN   NaN  ...   NaN   NaN   NaN   NaN   NaN
2          NaN   NaN   NaN   NaN   NaN  ...   NaN   NaN   NaN   NaN   NaN
3          NaN   NaN   NaN   NaN   NaN  ...   NaN   NaN   NaN   NaN   NaN
4          NaN   NaN   NaN   NaN   NaN  ...   NaN   NaN   NaN   NaN   NaN
5          NaN   NaN   NaN   NaN   NaN  ...   NaN   NaN   NaN   NaN   NaN

[5 rows x 3706 columns]

In [210]:
user_movie_matrix.count(axis=1)

User_id
1        53
2       129
3        51
4        21
5       198
       ...
6036    888
6037    202
6038     20
6039    123
6040    341
Length: 6040, dtype: int64

__Sparsity__

In [211]:
total = user_movie_matrix.size
rating = user_movie_matrix.count().sum()
sparsity = 1 - (rating/total)
print("Sparsity: ",sparsity)

Sparsity:  0.9553163743776871

In [212]:
a = df.groupby("Generes")["rating"].value_counts().sort_index(ascending=False).head(40)
a

Generes   rating
Western   5          1799
          4          2956
          3          2245
          2           847
          1           438
War       5          5652
          4          7999
          3          6244
          2          2527
          1          1292
Thriller  5         15145
          4         24456
          3         19277
          2          8596
          1          4871
Sci-Fi    5          7324
          4         10743
          3          7836
          2          3098
          1          1723
Romance   5         16869
          4         26815
          3         20475
          2          8853
          1          5041
Mystery   5          3488
          4          7091
          3          6275
          2          2671
          1          1279
Musical   5          3547
          4          5905
          3          4295
          2          1862
          1           986
Horror    5          8891
          4         12177
          3          9464
          2          3989
          1          1886
Name: count, dtype: int64

In [213]:
df['movie_rating'] = df.groupby('Movie_id')['rating'].count()
df['movie_rating']

0             NaN
1          2077.0
2           701.0
3           478.0
4           170.0
            ...
1000204       NaN
1000205       NaN
1000206       NaN
1000207       NaN
1000208       NaN
Name: movie_rating, Length: 1000209, dtype: float64

In [214]:
df['Movie_avg'] = df.groupby('Movie_id')['rating'].mean()
df['Movie_avg']

0               NaN
1          4.146846
2          3.201141
3          3.016736
4          2.729412
             ...
1000204         NaN
1000205         NaN
1000206         NaN
1000207         NaN
1000208         NaN
Name: Movie_avg, Length: 1000209, dtype: float64

In [215]:
df['Release_year'] = df['Title'].str.extract(r"\((\d{4})\)")
df['Release_year']

0          1975
1          1996
2          1964
3          2000
4          1998
           ...
1000204    1989
1000205    1992
1000206    1995
1000207    1982
1000208    1982
Name: Release_year, Length: 1000209, dtype: object

_Rating filter_

In [216]:
df['filter'] = df.groupby("Movie_id")["rating"].transform('count')
df[df['filter']>100].head(10)

   User_id  Movie_id  rating  ...  Movie_avg Release_year filter
0        1      1193       5  ...        NaN         1975   1725
1        1       661       3  ...   4.146846         1996    525
2        1       914       3  ...   3.201141         1964    636
3        1      3408       4  ...   3.016736         2000   1315
4        1      2355       5  ...   2.729412         1998   1703
5        1      1197       3  ...   3.006757         1987   2318
6        1      1287       5  ...   3.878723         1959    704
7        1      2804       5  ...   3.410480         1983   1352
8        1       594       4  ...   3.014706         1937    763
9        1       919       4  ...   2.656863         1939   1718

[10 rows x 14 columns]

In [217]:
df['Movie_stats'] = df.groupby('Movie_id')['Title'].first()
df['Movie_stats']

0                               NaN
1                  Toy Story (1995)
2                    Jumanji (1995)
3           Grumpier Old Men (1995)
4          Waiting to Exhale (1995)
                     ...
1000204                         NaN
1000205                         NaN
1000206                         NaN
1000207                         NaN
1000208                         NaN
Name: Movie_stats, Length: 1000209, dtype: object

In [218]:
df['avg_rating'] = df.groupby('Movie_id')['rating'].mean().sort_values(ascending=False).head(10)
df['avg_rating']

0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
           ..
1000204   NaN
1000205   NaN
1000206   NaN
1000207   NaN
1000208   NaN
Name: avg_rating, Length: 1000209, dtype: float64

In [219]:
df['filter'] = df.groupby("Movie_id")["rating"].transform('count')

df[df['filter']>=100].sort_values('avg_rating', ascending=False).head(10)

      User_id  Movie_id  ...                                Movie_stats  avg_rating
787         9      1233  ...         Gate of Heavenly Peace, The (1995)         5.0
989        10      3701  ...  Schlafes Bruder (Brother of Sleep) (1995)         5.0
1830       17      2268  ...                    Follow the Bitch (1998)         5.0
3172       24       303  ...                    Ulysses (Ulisse) (1954)         5.0
3233       24      3072  ...                       Smashing Time (1967)         5.0
3280       24      1674  ...                           Baby, The (1973)         5.0
3382       26      1689  ...                     Song of Freedom (1936)         5.0
3607       26       370  ...                   One Little Indian (1973)         5.0
3656       26      2942  ...                               Lured (1947)         5.0
3881       28       912  ...                   Bittersweet Motel (2000)         5.0

[10 rows x 16 columns]

In [220]:
df['filter'] = df.groupby("Movie_id")["rating"].transform('count')

df[df['filter']>=50].sort_values('avg_rating', ascending=False).head(10)

      User_id  Movie_id  ...                                Movie_stats  avg_rating
787         9      1233  ...         Gate of Heavenly Peace, The (1995)         5.0
989        10      3701  ...  Schlafes Bruder (Brother of Sleep) (1995)         5.0
1830       17      2268  ...                    Follow the Bitch (1998)         5.0
3172       24       303  ...                    Ulysses (Ulisse) (1954)         5.0
3233       24      3072  ...                       Smashing Time (1967)         5.0
3280       24      1674  ...                           Baby, The (1973)         5.0
3382       26      1689  ...                     Song of Freedom (1936)         5.0
3607       26       370  ...                   One Little Indian (1973)         5.0
3656       26      2942  ...                               Lured (1947)         5.0
3881       28       912  ...                   Bittersweet Motel (2000)         5.0

[10 rows x 16 columns]

In [221]:
df['filter'] = df.groupby("Movie_id")["rating"].transform('count')

df[df['filter']>=200].sort_values('avg_rating', ascending=False).head(10)

      User_id  Movie_id  ...                                Movie_stats  avg_rating
787         9      1233  ...         Gate of Heavenly Peace, The (1995)         5.0
989        10      3701  ...  Schlafes Bruder (Brother of Sleep) (1995)         5.0
1830       17      2268  ...                    Follow the Bitch (1998)         5.0
3172       24       303  ...                    Ulysses (Ulisse) (1954)         5.0
3233       24      3072  ...                       Smashing Time (1967)         5.0
3280       24      1674  ...                           Baby, The (1973)         5.0
3382       26      1689  ...                     Song of Freedom (1936)         5.0
3607       26       370  ...                   One Little Indian (1973)         5.0
3656       26      2942  ...                               Lured (1947)         5.0
3881       28       912  ...                   Bittersweet Motel (2000)         5.0

[10 rows x 16 columns]

In [222]:
df['filter'] = df.groupby("Movie_id")["rating"].transform('count')

df[df['filter']>=500].sort_values('avg_rating', ascending=False).head(10)

      User_id  Movie_id  ...                                Movie_stats  avg_rating
787         9      1233  ...         Gate of Heavenly Peace, The (1995)         5.0
989        10      3701  ...  Schlafes Bruder (Brother of Sleep) (1995)         5.0
1830       17      2268  ...                    Follow the Bitch (1998)         5.0
3233       24      3072  ...                       Smashing Time (1967)         5.0
3280       24      1674  ...                           Baby, The (1973)         5.0
3881       28       912  ...                   Bittersweet Motel (2000)         5.0
0           1      1193  ...                                        NaN         NaN
1           1       661  ...                           Toy Story (1995)         NaN
2           1       914  ...                             Jumanji (1995)         NaN
3           1      3408  ...                    Grumpier Old Men (1995)         NaN

[10 rows x 16 columns]

__Item Based Recommendation System__

In [223]:
from sklearn.metrics.pairwise import cosine_similarity

In [224]:
user_movie_matrix_filled = user_movie_matrix.fillna(0)

__Transpose the matrix__

In [225]:
movie_similarity = cosine_similarity(user_movie_matrix_filled.T)

In [226]:
movie_similarity.shape

(3706, 3706)

__Recommend Movie Function__

In [227]:
def recommend_movies(title , n=5):
    find_title = df1[df1["Title"] == title]['Movie_id'].values[0]
    address_in_matrix = user_movie_matrix_filled.columns.get_loc(find_title)

    similarity_score = movie_similarity[address_in_matrix]
    sorting = similarity_score.argsort()[::-1]

    top = sorting[1:6]

    Recommendation = user_movie_matrix_filled.columns[top]
    Recommended_Movies = df1[df1['Movie_id'].isin(Recommendation)]

    return Recommended_Movies['Title']

In [228]:
recommend_movies("Lassie (1994)",5)

7                 Tom and Huck (1995)
370                Richie Rich (1994)
498       Next Karate Kid, The (1994)
1008    Angels in the Outfield (1994)
3538         One Little Indian (1973)
Name: Title, dtype: object

__KNN__

In [229]:
from sklearn.neighbors import NearestNeighbors

In [230]:
movie_id = df1[df1["Title"] == "Lassie (1994)"]['Movie_id'].values[0]
movie_index = user_movie_matrix_filled.columns.get_loc(movie_id)

In [231]:
knn = NearestNeighbors(metric='cosine',algorithm='brute')

In [232]:
knn.fit(user_movie_matrix_filled.T)

NearestNeighbors(algorithm='brute', metric='cosine')

In [233]:
distances, indices = knn.kneighbors(user_movie_matrix_filled.T.iloc[movie_index].values.reshape(1,-1),n_neighbors=6)
print("Distance: ",distances)
print("Indices: ",indices)

Distance:  [[2.22044605e-16 7.40172079e-01 7.65674909e-01 7.78619168e-01
  7.88372513e-01 7.88802599e-01]]
Indices:  [[ 470 3367    7  956  364  488]]

In [234]:
recommeded_indices = indices[0][1:]
recommeded_indices

array([3367,    7,  956,  364,  488])

In [235]:
ids = user_movie_matrix_filled.columns[recommeded_indices]

In [236]:
recommendation = df1[df1['Movie_id'].isin(ids)]
recommendation[["Movie_id",'Title']]

      Movie_id                          Title
7            8            Tom and Huck (1995)
370        374             Richie Rich (1994)
498        502    Next Karate Kid, The (1994)
1008      1021  Angels in the Outfield (1994)
3538      3607       One Little Indian (1973)

__SVD Matrix__

In [237]:
from sklearn.decomposition import TruncatedSVD

In [238]:
svd = TruncatedSVD(n_components=50, random_state=42)

In [239]:
transformed = svd.fit_transform(user_movie_matrix_filled)

In [240]:
svd.components_.shape

(50, 3706)

In [241]:
transpose = svd.components_.T

In [242]:
transpose.shape

(3706, 50)

In [243]:
predicted_rating = transformed@svd.components_

In [244]:
predicted_rating.shape

(6040, 3706)

In [245]:
user_id = 1
user_index = user_movie_matrix.index.get_loc(user_id)
user_score = predicted_rating[user_index]

In [246]:
top_indices  =user_score.argsort()[::-1][:50]
top_indices

array([   0, 2898,  581,  513, 2162, 1848,  574,  858, 1178,  354,  309,
         33, 1025, 1900,  963, 1107,  580, 1190,  957,  964, 1838,  144,
       2599, 1897, 1915, 1899, 2651, 1108, 1906,  970, 1904,  582, 1727,
       2592,  346, 2556, 1135, 2511, 1767,  967, 2483,  253, 1956, 1574,
       2586, 1104, 2102, 1781,  853, 2710])

In [247]:
recommend_movie_ids = user_movie_matrix.columns[top_indices]

In [248]:
rated_movies = user_movie_matrix.loc[user_id].dropna().index

In [249]:
recommeded_movies = df1[df1['Movie_id'].isin(recommend_movie_ids) &
~df1['Movie_id'].isin(rated_movies)]

In [250]:
recommeded_movies.head(10)

      Movie_id                             Title      Generes
33          34                       Babe (1995)        Drama
315        318  Shawshank Redemption, The (1994)       Comedy
352        356               Forrest Gump (1994)  Documentary
360        364             Lion King, The (1994)       Comedy
592        596                  Pinocchio (1940)      Mystery
1019      1032        Alice in Wonderland (1951)       Comedy
1180      1198    Raiders of the Lost Ark (1981)    Film-Noir
1207      1225                    Amadeus (1984)       Comedy
1262      1282                   Fantasia (1940)        Drama
1878      1947            West Side Story (1961)       Comedy

__Train test split__

In [257]:
from sklearn.model_selection import train_test_split

In [258]:
train,test = train_test_split(df, test_size=0.2, random_state=42)

In [259]:
print("Train: ",train.shape)
print("Test: ",test.shape)

Train:  (800167, 16)
Test:  (200042, 16)

In [ ]:
train_matrix = train.pivot_table(
    index = 'User_id',
    columns = 'Movie_id',
    values = 'rating'
)
print("Train Matrix Shape: ",train_matrix.shape)

Train Matrix Shaape:  (6040, 3683)

__Train the Model on SVD__

In [261]:
train_matrix_filled = train_matrix.fillna(0)
evaluation = TruncatedSVD(
    n_components=50,
    random_state=42
)

train_transformed = evaluation.fit_transform(train_matrix_filled)
print("Transformed Shape: ", train_transformed.shape)

Transformed Shape:  (6040, 50)

In [263]:
predict_rating_evaluation = train_transformed @ evaluation.components_
print("Predict rating evaluation shape: ",predict_rating_evaluation.shape)

Predict rating evaluation shape:  (6040, 3683)

In [267]:
known_test = test[test['Movie_id'].isin(train_matrix.columns)]
print("Test: ",test.shape[0])
print("Test for known movies: ",known_test.shape[0])

Test:  200042
Test for known movies:  200016

In [268]:
known_test = known_test.copy()

known_test["predicted_rating"] = known_test.apply(
    lambda row: predict_rating_evaluation[
        train_matrix.index.get_loc(row["User_id"]),
        train_matrix.columns.get_loc(row["Movie_id"])
    ],
    axis=1
)

known_test[["User_id", "Movie_id", "rating", "predicted_rating"]].head()

        User_id  Movie_id  rating  predicted_rating
895536     5412      2683       2          1.429537
899739     5440       904       5         -0.139888
55687       368      3717       4          1.519507
63727       425      1721       4          0.758360
822011     4942      3697       1          1.000716

In [269]:
from sklearn.metrics import mean_squared_error
import numpy as np

rmse = np.sqrt(
    mean_squared_error(
        known_test["rating"],
        known_test["predicted_rating"]
    )
)

print("RMSE:", rmse)

RMSE: 2.7434045586313536

In [270]:
k = 10

relevant_test = known_test[known_test["rating"] >= 4]

print("Relevant test ratings:", relevant_test.shape[0])

Relevant test ratings: 115155

In [271]:
k = 10

precision_scores = []

for user_id in train_matrix.index:
    user_index = train_matrix.index.get_loc(user_id)
    
    scores = predict_rating_evaluation[user_index]
    
    rated_movies = train_matrix.loc[user_id].dropna().index
    
    movie_ids = train_matrix.columns
    
    candidates = movie_ids[~movie_ids.isin(rated_movies)]
    
    candidate_scores = scores[train_matrix.columns.isin(candidates)]
    
    top_indices = candidate_scores.argsort()[::-1][:k]
    
    recommended_movies = candidates[top_indices]
    
    relevant_movies = relevant_test[
        relevant_test["User_id"] == user_id
    ]["Movie_id"]
    
    hits = len(set(recommended_movies) & set(relevant_movies))
    
    precision = hits / k
    
    precision_scores.append(precision)

precision_at_10 = np.mean(precision_scores)

print("Precision@10:", precision_at_10)

Precision@10: 0.2702649006622517

In [272]:
recall_scores = []

for user_id in train_matrix.index:
    user_index = train_matrix.index.get_loc(user_id)
    
    scores = predict_rating_evaluation[user_index]
    
    rated_movies = train_matrix.loc[user_id].dropna().index
    
    movie_ids = train_matrix.columns
    candidates = movie_ids[~movie_ids.isin(rated_movies)]
    
    candidate_scores = scores[train_matrix.columns.isin(candidates)]
    
    top_indices = candidate_scores.argsort()[::-1][:10]
    
    recommended_movies = candidates[top_indices]
    
    relevant_movies = relevant_test[
        relevant_test["User_id"] == user_id
    ]["Movie_id"]
    
    if len(relevant_movies) > 0:
        hits = len(set(recommended_movies) & set(relevant_movies))
        recall = hits / len(relevant_movies)
        recall_scores.append(recall)

recall_at_10 = np.mean(recall_scores)

print("Recall@10:", recall_at_10)

Recall@10: 0.19581087283640725

In [273]:
comparison = pd.DataFrame({
    "Model": [
        "Cosine Similarity",
        "Item-Based KNN",
        "SVD"
    ],
    "Approach": [
        "Item-based",
        "Item-based",
        "Latent-factor"
    ],
    "RMSE": [
        "Not evaluated",
        "Not evaluated",
        2.743
    ],
    "Precision@10": [
        "Not evaluated",
        "Not evaluated",
        0.2703
    ],
    "Recall@10": [
        "Not evaluated",
        "Not evaluated",
        0.1958
    ]
})

comparison

               Model       Approach  ...   Precision@10      Recall@10
0  Cosine Similarity     Item-based  ...  Not evaluated  Not evaluated
1     Item-Based KNN     Item-based  ...  Not evaluated  Not evaluated
2                SVD  Latent-factor  ...         0.2703         0.1958

[3 rows x 5 columns]

In [274]:
def recommend_svd(user_id, n=10):
    
    user_index = train_matrix.index.get_loc(user_id)
    
    user_scores = predict_rating_evaluation[user_index]
    
    rated_movies = train_matrix.loc[user_id].dropna().index
    
    movie_ids = train_matrix.columns
    
    candidate_movies = movie_ids[~movie_ids.isin(rated_movies)]
    
    candidate_scores = user_scores[train_matrix.columns.isin(candidate_movies)]
    
    top_indices = candidate_scores.argsort()[::-1][:n]
    
    recommended_movie_ids = candidate_movies[top_indices]
    
    recommended_movies = df1[
        df1["Movie_id"].isin(recommended_movie_ids)
    ]
    
    return recommended_movies[["Movie_id", "Title"]]

In [275]:
recommend_svd(1, 10)

      Movie_id                       Title
33          34                 Babe (1995)
352        356         Forrest Gump (1994)
360        364       Lion King, The (1994)
1949      2018                Bambi (1942)
2009      2078     Jungle Book, The (1967)
2012      2081  Little Mermaid, The (1989)
2027      2096      Sleeping Beauty (1959)
2647      2716         Ghostbusters (1984)
2692      2761      Iron Giant, The (1999)
3682      3751          Chicken Run (2000)